# Generated by Django 3.2 on 2021-05-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_crawl', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('last_crawl', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=2000, null=True)),
                ('link', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(null=True)),
                ('view_count', models.IntegerField(null=True)),
                ('publish_data', models.DateTimeField(null=True)),
                ('last_crawl', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.channel')),
            ],
        ),
    ]
