# Generated by Django 3.2 on 2021-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_crawl',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
