# Generated by Django 3.2 on 2021-06-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_last_crawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_crawl',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='last_crawl',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
