# Generated by Django 3.2 on 2021-06-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210601_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_Video',
            fields=[
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=2000, null=True)),
                ('link', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(null=True)),
                ('view_count', models.IntegerField(null=True)),
                ('publish_data', models.DateTimeField(null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.channel')),
            ],
        ),
    ]
